CREATE TABLE IF NOT EXISTS public.favorites (
    favorite_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id INTEGER NOT NULL,
    inv_id INTEGER NOT NULL,
    date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorites_pkey PRIMARY KEY (favorite_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account(account_id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
    CONSTRAINT unique_favorite UNIQUE (account_id, inv_id)
);